version: "3.9"
services:
  web:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5000:5000"
    env_file: ./frontend/.env-docker
    depends_on:
      - "api"
  api:
    build:
      context: ./cluetracker
      dockerfile: ./Dockerfile
    volumes:
      - ./cluetracker:/usr/src/app
    ports:
      - "8000:8000"
    env_file: ./cluetracker/.env-docker
    depends_on:
      - "db"
  db:
    image: postgres:13-alpine
    volumes:
      - "/var/lib/postgresql/data"
    env_file: .env-docker-postgres
