version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file: .env-docker
    depends_on:
      - "db"
  db:
    image: postgres:13-alpine
    volumes:
      - "/var/lib/postgresql/data"
    env_file: .env-docker-postgres
