# Generated by Django 3.2.7 on 2021-09-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210906_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='have',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haves', to='games.card'),
        ),
        migrations.AlterField(
            model_name='have',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haves', to='games.player'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='games.card'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='games.player'),
        ),
        migrations.AlterField(
            model_name='show',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_shows', to='games.card'),
        ),
        migrations.AlterField(
            model_name='show',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='games.player'),
        ),
        migrations.AlterField(
            model_name='show',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_shows', to='games.card'),
        ),
        migrations.AlterField(
            model_name='show',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_shows', to='games.card'),
        ),
    ]
